spring.application.name=backend

# ==========================================================
# Database (MariaDB) 설정
# ==========================================================
spring.datasource.url=jdbc:mariadb://localhost:3310/connected_m
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate 설정
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================================
# Swagger (API 문서) 설정
# ==========================================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.show-data-rest=true

jwt.secret=your_very_long_and_secure_random_string_secret_key_32_chars
jwt.expiration=3600000

# TMDB API ??
spring.config.import=optional:classpath:api-keys.properties
tmdb.api.key=59369bd668a8f9e0cc13ab676bfcdc7c
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1OTM2OWJkNjY4YThmOWUwY2MxM2FiNjc2YmZjZGM3YyIsIm5iZiI6MTc3NDgzMzUwMC41NTgsInN1YiI6IjY5YzljZjVjNjE2YWEzMDk3ZmNlMzgzYyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Q_9s0lk-AFAKApowSutOan5MZudJeeeIq1xiTZZCh6g
tmdb.api.base-url=https://api.themoviedb.org/3

# ==========================================================
# Kakao OAuth2 ??
# ==========================================================
spring.security.oauth2.client.registration.kakao.client-id=0ce079771e8fa48fe3aebd3ed1f43d2a
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.client-secret=Jw608zvrVqqpTmoP4hN9h5ut8bJ55J2J
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code

spring.security.oauth2.client.registration.kakao.redirect-uri=http://localhost:8080/login/oauth2/code/kakao
spring.security.oauth2.client.registration.kakao.scope=profile_nickname
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id

# ??
# Google OAuth2 Settings
spring.security.oauth2.client.registration.google.client-id=259242355746-7mqml86hsgoo3asao679nb1cvvohm7hm.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email